### ISSUE TITLE
Sorting of entries in the Guard Dashboard 

### ISSUE THREAD

**Issue by palashmunshi** [palashmunshi/Gatepass-Portal#19]
The checkin and checkout pages have multiple entries. These entries are not sorted right now. 

**Goal:** 
**1. Checkin Page:** To sort the entries on arrival date/time. It should be in ascending order i.e. early arrival date/time should come first in the list.
**2. Checkout Page:**: To sort the entries on the departure date/time. It should be in ascending order i.e. early departure date/time should come first in the list.

**Comment by Kahitoz** [comment]
I have sorted it, Thanks, regards - kshitiz sinha
