### ISSUE TITLE
API for group-subgroup and implement it in UI

### ISSUE THREAD

**Issue by palashmunshi** [palashmunshi/Gatepass-Portal#36]
API to be made for getting group and subgroup list which is to be displayed on the group/subgroup page on the admin side.
**TASK:**
To create query, function, and route on the server side and test it using postman
**Outcome:** the result should be a JSON file containing all the group details and another JSON file containing all subgroup details

**Comment by Kahitoz** [comment]
API done along with the fetch part, now the data is also been shown, request to change the title of the issue or create a new issue , thanks 
Regards Kshitiz
